### ISSUE TITLE
Improve readme to show steps to install package from NPM

### ISSUE THREAD

**Issue by ChuckJonas** [kevinohara80/sfdc-pkg-postinstall#1]
It would be helpful to add steps on how install a package that leverages this post-install from NPM.

Example: if I wanted to install your trigger framework in my org, what is the best/quickest path to doing so?

Also, might be nice to include steps to update.

**Comment by kevinohara80** [comment]
You simply install a SFDC package the same way you install any node package:

`npm install <pkg_name>`

So for the trigger handler:

`npm install sfdc-trigger-handler`

It'd be a good idea to familiarize yourself with npm as the install/update/etc semantics are the same. If you want to clarify any of this in the readme, please feel free to submit a pull request. I'd be happy to merge it.

**Comment by ChuckJonas** [comment]
ohhh I was just confused on how this worked.  I missed this part: 

> This does not deploy any code upon install. It simply merges the code into your projects src dir. You can use something like dmc to deploy your code or other common IDE's and tools like MavensMate.

and thought this was relying on DMC to deploy code on when install is run. 

Makes perfect sense now.  thanks

**Comment by ChuckJonas** [comment]
having a `node_modules` folder in my mavensmate project sort of feels odd but I guess there is no harm there...

**Comment by kevinohara80** [comment]
Just make sure you `gitignore` the `node_modules` dir!
